import React, { useState } from 'react'
import { Modal, ModalBody, ModalFooter, ModalHeader } from 'react-bootstrap'
import { Link } from 'react-router-dom'

function AddExamPermit() {

    const [input_exam_permit, setInput_Exam_Permit] = useState([])

    const inputData = (e) => {
        setInput_Exam_Permit({
            ...input_exam_permit,
            [e.target.name]: e.target.value
        })
    }

    const { generated_by } = input_exam_permit

    return (
        <>
            <Modal
                show={true}
                centered
                size='xl'
            >
                <ModalHeader className='text-white' style={{backgroundColor: '#031B5B'}}>
                    <div className='container-fluild'>
                        <h6>ADD EXAM PERMIT</h6>
                    </div>
                </ModalHeader>
                <ModalBody>
                    <div className='row'>
                        <div className='col-4'>
                            <h6><b>Generated By</b></h6>
                            <select className='form-control' name='generated_by' onChange={inputData}>
                                <option></option>
                                <option value='Student'>Student</option>
                                <option value='Block'>Block</option>
                            </select>
                        </div>
                        <div className='col-4'>
                            {
                                generated_by === 'Student' ? 
                                    <>
                                        <h6>Student ID</h6>
                                        <select name='student_id' className='form-control' onChange={inputData}>
                                            <option></option>
                                        </select>
                                    </>
                                :
                                 generated_by === 'Block' ?
                                    <>
                                        <h6>Block ID</h6>
                                        <select name='block_id' className='form-control' onChange={inputData}>
                                            <option></option>
                                        </select>
                                    </>
                                : 
                                    <>
                                        <h6>Student ID</h6>
                                        <select name='student_id' className='form-control' disabled>
                                            <option></option>
                                        </select>
                                    </>
                            }
                        </div>
                        <div className='col-4'>
                            <h6>Registrar</h6>
                            <select className='form-control' name='registrar' onChange={inputData}>
                                <option></option>
                            </select>
                        </div>
                        <div className='col-4 mt-2'>
                            <h6>Cashier</h6>
                            <select className='form-control' name='cashier' onChange={inputData}>
                                <option></option>
                            </select>
                        </div>
                        <div className='col-4 mt-2'>
                            <h6>Exam Period</h6>
                            <select className='form-control' name='exam_period' onChange={inputData}>
                                <option></option>
                                <option value='Prelim Exam'>Prelim Exam</option>
                                <option value='Midterm Exam'>Midterm Exam</option>
                                <option value='Final Exam'>Final Exam</option>
                            </select>
                        </div>
                        <div className='col-4 mt-2'>
                            <h6>AY</h6>
                            <select className='form-control' name='a_y' onChange={inputData}>
                                <option></option>
                            </select>
                        </div>
                        <div className='col-4 mt-2'>
                            <h6>Semester</h6>
                            <select className='form-control' name='semester' onChange={inputData}>
                                <option></option>
                                <option value='First Semester'>First Semester</option>
                                <option value='Second Semester'>Second Semester</option>
                                <option value='Third Semester'>Third Semester</option>
                                <option value='Summer'>Summer</option>
                            </select>
                        </div>
                    </div>
                </ModalBody>
                <ModalFooter className='text-white' style={{backgroundColor: '#031B5B'}}>
                    <Link to='../' className='btn btn-secondary'>CLOSE</Link>
                    <button className='btn btn-primary'>GENERATE</button>
                </ModalFooter>
            </Modal>
        </>
    )
}

export default AddExamPermit
